# Generated by Django 5.1.2 on 2024-10-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
