# Generated by Django 5.1.2 on 2024-10-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticketatendido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketatendido',
            name='ticket',
        ),
        migrations.AddField(
            model_name='ticketatendido',
            name='apellido',
            field=models.CharField(default='g', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketatendido',
            name='dni',
            field=models.CharField(default=22, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketatendido',
            name='nombre',
            field=models.CharField(default='sw', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketatendido',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticketatendido',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
